---
# This workflow will do a clean install of node dependencies and deploy to AWS.

name: Staging Deploy
run-name: Publish staging site

on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo
  pull-requests: write # required to comment on the PR with the staging URL

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json

    - name: Configure sustainable npm
      uses: lowlydba/sustainable-npm@31d51025884f424f58f22e4e6578178bb4e79632 # v3.0.0

    - name: Install
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm test

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json

    - name: Configure sustainable npm
      uses: lowlydba/sustainable-npm@31d51025884f424f58f22e4e6578178bb4e79632 # v3.0.0

    - name: Install
      # install scripts disabled by sustainable-npm, so run postinstall manually & safely just for this package
      run: |
        npm ci
        npm run postinstall

    - name: Build
      run: npm run build
      env:
        BASEURL: ${{ github.event.repository.name }}/pr/${{ github.event.number }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: build-artifact
        path: out
        if-no-files-found: error

  deploy:
    name: Deploy
    runs-on: ubuntu-slim
    needs: [test, build]
    environment:
      name: staging
      url: ${{ steps.deploy_url.outputs.url }}

    steps:
      - name: Set deploy URL
        id: deploy_url
        run: echo "url=https://staging.overturemaps.org/${{ github.event.repository.name }}/pr/${{ github.event.number }}/index.html" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::763944545891:role/pages-staging-oidc-overturemaps
          aws-region: us-west-2

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-artifact
          path: build

      - name: Copy to S3
        run: |
          aws s3 sync --delete build s3://overture-managed-staging-usw2/gh-pages/${{ github.event.repository.name }}/pr/${{ github.event.number }}/

      - name: Bust the Cache
        run: aws cloudfront create-invalidation --distribution-id E1KP2IN0H2RGGT --paths "/${{ github.event.repository.name }}/pr/${{ github.event.number }}/*"

      - name: Get deploy timestamp
        id: timestamp
        run: |
          echo "time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "short-sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@70d2764d1a7d5d9560b100cbea0077fc8f633987 # v3.0.2
        with:
          message: |
            ## 🗺️ Overture Maps Explorer preview is live!

            |                |                                                                                                                                                       |
            |----------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|
            | 🌍 **Preview** | ${{ steps.deploy_url.outputs.url }}                                                                                                                   |
            | 🕐 **Updated** | ${{ steps.timestamp.outputs.time }}                                                                                                                   |
            | 📝 **Commit**  | [${{ steps.timestamp.outputs.short-sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }})        |

            > [!NOTE]
            > ♻️ This preview updates automatically with each push to this PR.
